### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-js-arrays#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://ravedave.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/js-arrays/1) criteria:
- [x] The current number of todo items is always displayed below the list of todos.
- [x] A "Clear all" button exists, which will clear all todos when clicked.
- [x] A "Can't decide!" button exists, which picks a random todo item from the user's list and shows it in an alert. (Hint: you may have to use Google here.)
- [x](Optional) Each todo item contains two additional buttons: "↑" and "↓", which move the item up or down in the list, respectively. If the item is already at the top or bottom, then the button to move it further up or down, respectively, should not appear. Again, Google will likely be helpful here.

**Comment by ackleyd1** [comment]
There is a file called games.txt. This is for the future so I can use that Ajax technique you were referring to when google comes up with search suggestions. I want to build a similar thing for the input

**Comment by ackleyd1** [comment]
It has the string of every gamecube game ever made

**Comment by chrisvfritz** [comment]
Very nice! I also like the descriptive comments. :tada: This certainly meets all of the base criteria, but since you're doing so well, I'm going to push you a _little_ farther. Here are some additional criteria I want you to meet:
- If an item is already at the top or bottom, then the button to move it further up or down, respectively, should not appear. For this, `if` statements or possibly even [ternaries](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) (a new concept for _inline_ `if-else` expressions) will be useful.
- If the input is blank or just contains spaces, hitting the `Enter` key should do nothing. For this, you may find the [`trim` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim) useful.

Please don't hesitate to let me know if you have any questions. :smiley:

**Comment by ackleyd1** [comment]
Actually didn't run into any problems fixing this... makes it a lot better. Any other suggestions? Starting to get a handle on JavaScript. Hosted at the same link

**Comment by chrisvfritz** [comment]
Wow! OK, here's another one then. :smile:

I want to be able to edit each todo. When I click on the text of a todo, it should turn into a text input. After I finish editing, pressing enter should save the changes I made and re-render the list of todos as normal text.

Try that one and if you have any questions, please don't hesitate to let me know!

**Comment by ackleyd1** [comment]
Do i have to make changes to my HTML for this event to happen correctly? I'm thinking I should make some kind of p element inside my li element so I can update it only when the text is clicked on via clickedElement.className. If there are ways to get around this, what suggestions do you have? perhaps another property for clickedElement I'm thinking.

**Comment by ackleyd1** [comment]
This is how I handled it, check it out when you can!

**Comment by chrisvfritz** [comment]
Well done! There are a few areas for improvement though, that I detailed in [my comments on this commit](https://github.com/ackleyd1/codelab-js-arrays/commit/5b29cf5484e38abfe2ea32a054cbe1586c29baba).

**Comment by ackleyd1** [comment]
OK so i think I fixed everything and I also handled things when the Can't decide button was pressed and there were either 1 or no games in the array. You shouldnt need a random picker if there are a) no games to pick from or b) 1 game to pick from. Also I kinda want to set the cursor automatically at the end of the input field but I couldnt find a way by googling that seemed simple. I feel like theres a simple way to handle that. What do you think?

**Comment by chrisvfritz** [comment]
- `element.select()` is a great method for highlight the text. I'll often do that right after `element.focus()` to replicate the behavior people are used to when renaming files in most operating systems
- What were you trying to do with `onfocus="' + this.value + '"`?
- What about the escape key to cancel the rename?? :stuck_out_tongue: I want to escape!
- How about hiding the random game picker when you shouldn't use it, rather than displaying an error message on click?

**Comment by ackleyd1** [comment]
OK thats the thing I forgot. For some reason it doesnt recognize the escape key. Also, the onfocus was my first attempt at what .focus() does but I forgot that I kept it after I found the right solution. I just got rid of it. Ill try out the suggestion for the random game picker

**Comment by chrisvfritz** [comment]
Sounds good. :smiley: Let me know when it's ready for another look. As for the enter key, try it with `keyup` or `keydown` instead of `keypress` and see if that works.

**Comment by ackleyd1** [comment]
![image](https://cloud.githubusercontent.com/assets/12974323/13832037/a928ad2c-ebae-11e5-9949-f3d3f35f8060.png)

**Comment by chrisvfritz** [comment]
Very nice! :tada: Everything works - which is definitely the _most_ important thing. And this is most absolutely worth of a :shipit:. Just to expand your mind a little more though, I performed a refactor below. Most notably, I:
- Split the code into several sections
- Added more comments
- Reduced duplicated code (places where we're doing the exact same thing)
- Sometimes refactored to use simpler solutions

Let me know what you think. In the comments at the very top, I link to some new concepts/tools I used to achieve some of the refactor. :smiley: 

``` js
// Some new concepts here
//
// - Ternaries: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator
// - document.createElement: https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
// - element.appendChild: https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild
// - More equality operators: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

// -------------
// INITIAL STATE
// -------------

var games = []

// --------
// ELEMENTS
// --------

var clearAll = document.getElementById('clear')
var randomGame = document.getElementById('random')
var newGameInput = document.getElementById('input')
var gamesList = document.getElementById('games')
var gameNumber = document.getElementById('gameNumber')

// ------
// RENDER
// ------

function renderGames () {
  gamesList.innerHTML = games.map(function (game, index) {
    // Base game HTML
    var gameHTML =
      '<span class="game">' + game + '</span>' +
      '<button class="clear" data-index="' + index + '">X</button>'
    // Button to the move the game down in the list
    if (index !== games.length - 1) {
      gameHTML += '<button class="down" data-index="' + index + '">↓</button>'
    }
    // Button to the move the game up in the list
    if (index !== 0) {
      gameHTML += '<button class="up" data-index="' + index + '">↑</button>'
    }
    // Final HTML wrapped in an `li` element
    return '<li>' + gameHTML + '</li>'
  }).join('')
  // Update the displayed number of games
  gameNumber.innerHTML = 'Number of games to play: ' + games.length
  // Update whether the random game button is visible
  randomGame.style.display = games.length > 1 ? 'inline' : 'none'
  // Update whether the clear button is visible
  clearAll.style.display = games.length > 0 ? 'inline' : 'none'
}

// ----------
// INITIALIZE
// ----------

renderGames()

// -------
// ACTIONS
// -------

function moveGame (direction, index) {
  var offsetIndex = direction === 'up' ? 1 : -1
  var tempGame = games[index + offsetIndex]
  games[index + offsetIndex] = games[index]
  games[index] = tempGame
  renderGames()
}

function deleteGame (index) {
  games.splice(index, 1)
  renderGames()
}

function editGame (gameElement) {
  var gameText = gameElement.innerHTML

  // Create a new input element
  var editGameInput = document.createElement('input')
  editGameInput.value = gameText

  // Replace the contents of gameElement with the input
  gameElement.innerHTML = ''
  gameElement.appendChild(editGameInput)

  // Focus and select the input
  editGameInput.focus()
  editGameInput.select()

  editGameInput.onkeyup = function (event) {
    // On keyup ENTER
    if (event.which === 13) {
      // Unless the input is blank
      if (this.value.trim() !== '') {
        // Rename the todo
        games.splice(games.indexOf(gameText), 1, this.value)
        renderGames()
      }
    }
    // On keyup ESCAPE
    else if (event.which === 27) {
      // Cancel edit by re-rendering
      renderGames()
    }
  }
}

// ------
// EVENTS
// ------

gamesList.onclick = function (event) {
  var clickedElement = event.target
  var clickedIndex = parseInt(clickedElement.dataset.index)

  // Delete game
  if (clickedElement.className === 'clear') {
    deleteGame(clickedIndex)
  }

  // Move game up
  else if (clickedElement.className === 'up') {
    moveGame('up', clickedIndex)
  }

  // Move game down
  else if (clickedElement.className === 'down') {
    moveGame('down', clickedIndex)
  }

  // Edit game
  else if (clickedElement.className === 'game') {
    editGame(clickedElement)
  }
}

// Clear all games
clearAll.onclick = function () {
  games = []
  renderGames()
}

// Choose random game
randomGame.onclick = function () {
  // Alert the user of a random game they should play
  alert(
    'You should play ' +
    games[Math.floor(Math.random() * games.length)]
  )
}

// Add new game
newGameInput.onkeyup = function (event) {
  // On keyup ENTER
  if (event.which === 13) {
    // Unless the input is blank
    if (this.value.trim() !== '') {
      // Add the new todo
      games.push(this.value)
      // Clear the new todo input
      this.value = ''
      renderGames()
    }
  }
}
```
